FROM openjdk:8u212-jre
MAINTAINER Marshal 453607106@qq.com

COPY ./target/epoch-gateway-1.0-RELEASE.jar /webapps/epoch-gateway-1.0-RELEASE.jar

ENTRYPOINT ["java", "-jar", "/webapps/epoch-gateway-1.0-RELEASE.jar"]
