FROM openjdk:8u212-jre
MAINTAINER Marshal 453607106@qq.com

COPY ./target/epoch-generator-1.0.0-SNAPSHOT.jar /webapps/epoch-generator-1.0.0-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "/webapps/epoch-generator-1.0.0-SNAPSHOT.jar"]
